[package]
name = "db"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sled = "0.34"
bincode = "1.0"
serde = { version = "1.0", features = ["derive"] }
indexmap = "2.2"
log = "0.4"
derivative = "2.2"
derive-getters = "0.3"


